language: node_js

node_js:
  - "5"
  - "6"
  - "7"
  - "stable"

sudo: false

cache:
  yarn: true

script:
  - npm run lint
  - npm run build
  # Change script to `npm test` when tests are all written
